name: 软件建议
description: 你发现了新大陆？
labels: [新软件]
body:
  # - type: checkboxes
  #   attributes:
  #     label: 请先确认：
  #     description: 请确认您已按照以下步骤操作
  #     options:
  #       - label: 我明白 [发工单必须遵守这些内容](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md)。
  #         required: true
  - type: input
    attributes:
      label: 软件名
    validations:
      required: true
  - type: input
    attributes:
      label: 软件官网
    validations:
      required: true
  - type: input
    attributes:
      label: 最新发布日期
    validations:
      required: true
  - type: input
    attributes:
      label: 一句话描述软件主要用途
    validations:
      required: true
  - type: textarea
    attributes:
      label: 软件下载链接
      description: 如有不同版本多个链接，每行一个
    validations:
      required: false
  - type: dropdown
    attributes:
      label: 商业模式
      multiple: true
      options:
        - 免费
        - 买断
        - 订阅
    validations:
      required: true
