name: Brew Tap
description: Homebrew Tap

inputs:
  HOMEBREW_GITHUB_API_TOKEN:
    description: "Homebrew GitHub API Token"
    required: true

runs:
  using: "composite"

  steps:
    - name: Add Tap
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ inputs.HOMEBREW_GITHUB_API_TOKEN }}
      shell: bash -ieo pipefail {0}
      run: |
        brew tap brewforge/chinese
        brew update

    - name: Install Homebrew's dependencies
      shell: bash -ieo pipefail {0}
      run: |
        brew install ripgrep sd gcc parallel coreutils
        brew unlink coreutils && brew link coreutils
        brew install-bundler-gems --groups "audit,style"

    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        global: true
        name: "Brewforge-Bot"
        email: "brewforge-bot@aliyun.com"
        token: "${{ inputs.HOMEBREW_GITHUB_API_TOKEN }}"

    - name: show git context
      shell: bash -ieo pipefail {0}
      run: |
        cat $HOME/.gitconfig
        cat $GITHUB_ENV
